// [20261006_T8_PackagingSlimdown] Ticket #422 (spec #412 decision 5): the
// embedded-Python dependency swap ships under SBOM pin discipline — every
// wheel is pinned with its sha256. Two committed artifacts carry that:
//   scripts/embedded-python/requirements.lock  — pip --require-hashes input
//   scripts/embedded-python/wheel-manifest.json — per-wheel SBOM detail
// Both are generated by scripts/embedded-python/generate-wheel-manifest.js
// (pip download per platform → sha256); the lock and the manifest must
// never drift apart, so this test cross-checks them. RED first: fails until
// the artifacts exist.
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const EMBEDDED_DIR = path.resolve(__dirname, "../../scripts/embedded-python");
const LOCK_PATH = path.join(EMBEDDED_DIR, "requirements.lock");
const MANIFEST_PATH = path.join(EMBEDDED_DIR, "wheel-manifest.json");

const SHA256_RE = /^[0-9a-f]{64}$/;

/** PEP 503 normalization — wheel filenames use underscores, PyPI metadata
 * uses dashes; the lock/manifest carry the wheel-spelling. */
function normalizeName(name: string): string {
  return name.toLowerCase().replace(/_/g, "-");
}

interface LockEntry {
  name: string;
  version: string;
  hashes: string[];
}

/** Parse a pip requirements file: `name==version --hash=sha256:...` lines
 * (inline hash format — pip ≥26 ignores continuation-style hash lines).
 * Comments/blank lines ignored. */
function parseLock(content: string): LockEntry[] {
  const entries: LockEntry[] = [];
  for (const rawLine of content.split("\n")) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    if (line.startsWith("--")) continue; // global options
    const tokens = line.split(/\s+/);
    const match = tokens[0]!.match(/^([A-Za-z0-9_.-]+)==([^\s]+)$/);
    if (!match) throw new Error(`unpinned or malformed lock line: ${line}`);
    const hashes = tokens
      .slice(1)
      .filter((token) => token.startsWith("--hash=sha256:"))
      .map((token) => token.replace(/^--hash=sha256:/, ""));
    if (tokens.length !== hashes.length + 1) {
      throw new Error(`unexpected token in lock line: ${line}`);
    }
    entries.push({ name: match[1]!, version: match[2]!, hashes });
  }
  return entries;
}

interface WheelRecord {
  filename: string;
  sha256: string;
  platform_tag: string;
}

interface WheelManifest {
  generated_utc: string;
  python_version: string;
  platforms: string[];
  packages: { name: string; version: string; wheels: WheelRecord[] }[];
}

describe("[20261006_T8_PackagingSlimdown] embedded python wheel SBOM", () => {
  const lockExists = fs.existsSync(LOCK_PATH);
  const manifestExists = fs.existsSync(MANIFEST_PATH);

  it("commits both SBOM artifacts", () => {
    expect(lockExists, `missing ${LOCK_PATH}`).toBe(true);
    expect(manifestExists, `missing ${MANIFEST_PATH}`).toBe(true);
  });

  it.skipIf(!lockExists)("pins every requirement with a sha256 hash", () => {
    const entries = parseLock(fs.readFileSync(LOCK_PATH, "utf8"));
    expect(entries.length).toBeGreaterThan(5);
    for (const entry of entries) {
      expect(
        entry.hashes.length,
        `${entry.name}==${entry.version} has no --hash`,
      ).toBeGreaterThan(0);
      for (const hash of entry.hashes) {
        expect(hash, `${entry.name}: bad hash ${hash}`).toMatch(SHA256_RE);
      }
    }
  });

  it.skipIf(!lockExists)(
    "pins the ONNX runtime stack and excludes the torch generation",
    () => {
      const entries = parseLock(fs.readFileSync(LOCK_PATH, "utf8"));
      const versionOf = (name: string): string | null =>
        entries.find((entry) => normalizeName(entry.name) === name)?.version ??
        null;
      // Versions mirror scripts/onnx-export/requirements-export.txt and
      // scripts/onnx-spike/requirements-runtime.txt (the T1/T415 pins the
      // exported artifacts were produced and verified against).
      expect(versionOf("funasr-onnx")).toBe("0.4.3");
      expect(versionOf("onnxruntime")).toBe("1.30.0");
      expect(versionOf("soundfile")).toBe("0.14.0");
      expect(versionOf("numpy")).toBe("1.26.4");
      expect(versionOf("librosa")).toBe("0.11.0");
      expect(versionOf("jieba")).toBe("0.42.1");
      // Dev tooling by repo convention (run-python-tests.js measures the
      // suite inside the resolved runtime env) — pinned like every wheel.
      expect(versionOf("coverage")).toBe("7.16.2");

      const names = entries.map((entry) => normalizeName(entry.name));
      for (const banned of [
        "torch",
        "torchaudio",
        "torchvision",
        "funasr",
        "modelscope",
      ]) {
        expect(
          names,
          `${banned} must not ride along in the runtime env`,
        ).not.toContain(banned);
      }
      // numba/llvmlite stay in the lock (pip --require-hashes needs the
      // full closure; packaging prunes them behind the import gate).
      expect(names).toContain("numba");
      expect(names).toContain("llvmlite");
    },
  );

  it.skipIf(!lockExists || !manifestExists)(
    "keeps lock and manifest in lockstep (same name/version set, same hashes)",
    () => {
      const entries = parseLock(fs.readFileSync(LOCK_PATH, "utf8"));
      const manifest = JSON.parse(
        fs.readFileSync(MANIFEST_PATH, "utf8"),
      ) as WheelManifest;

      const lockByName = new Map(entries.map((entry) => [entry.name, entry]));
      const manifestByName = new Map(
        manifest.packages.map((pkg) => [pkg.name, pkg]),
      );
      expect(new Set(lockByName.keys())).toEqual(
        new Set(manifestByName.keys()),
      );
      for (const [name, entry] of lockByName) {
        expect(
          manifestByName.get(name)!.version,
          `${name} version drifted between lock and manifest`,
        ).toBe(entry.version);
        const manifestHashes = manifestByName
          .get(name)!
          .wheels.map((wheel) => wheel.sha256)
          .sort();
        expect(manifestHashes).toEqual([...entry.hashes].sort());
      }
    },
  );

  it.skipIf(!manifestExists)(
    "covers both shipping platforms and only shipping-platform wheels",
    () => {
      const manifest = JSON.parse(
        fs.readFileSync(MANIFEST_PATH, "utf8"),
      ) as WheelManifest;
      expect(manifest.python_version).toBe("3.11");

      let sawMacArm = false;
      let sawWinX64 = false;
      for (const pkg of manifest.packages) {
        for (const wheel of pkg.wheels) {
          expect(wheel.filename, wheel.filename).toMatch(/\.whl$/);
          expect(wheel.sha256).toMatch(SHA256_RE);
          // Wheel platform tags the packaged envs can actually consume:
          // macOS arm64 (incl. universal2) and Windows x64; "any" for pure
          // wheels. A linux-only or win32 wheel here would break CI.
          const platPart = wheel.platform_tag;
          const parts = platPart.split(".");
          for (const part of parts) {
            expect(part).toMatch(
              /^(macosx_[\d_]+_(arm64|universal2)|win_amd64|any)$/,
            );
          }
          if (/macosx/.test(platPart)) sawMacArm = true;
          if (/win_amd64/.test(platPart)) sawWinX64 = true;
        }
      }
      expect(
        sawMacArm,
        "no macOS arm64 wheel recorded — the mac env would be unpinnable",
      ).toBe(true);
      expect(
        sawWinX64,
        "no win_amd64 wheel recorded — the win env would be unpinnable",
      ).toBe(true);
    },
  );
});
